camunda:
  client:
    mode: saas
    auth:
      client-id: 3yx76oeP7Me6j9wJMkqyQYrrHKCsiiF9
      client-secret: PLW7lCGtJNHWzD0Ms4QT-yQh_IXoBpxIZnFSq1xMVgA9rb7AFOS1zk6Nj0lalDB~
    cloud:
      cluster-id: 493871eb-c719-4acf-a16e-9cce93d2ece3
      region: lhr-1
  task-list-url: https://${camunda.client.cloud.region}.tasklist.camunda.io/${camunda.client.cloud.cluster-id}/
  zeebe-rest-address: https://${camunda.client.cloud.region}.zeebe.camunda.io/${camunda.client.cloud.cluster-id}/
  process-definition-id: createInstanceProcessId

server:
  port: 8888
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            #            scope: .default
            scope: openid, profile, email, User.Read
            redirect-uri: http://localhost:8888/login/oauth2/code/azure
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/fc617c24-f3a3-45ef-9211-2c88d6a060e8/v2.0
            authorization-uri: https://login.microsoftonline.com/fc617c24-f3a3-45ef-9211-2c88d6a060e8/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/fc617c24-f3a3-45ef-9211-2c88d6a060e8/oauth2/v2.0/token
            user-name-attribute: name

#redirect-uri: http://localhost:8888/login/oauth2/code/azure


  datasource:
    url: jdbc:postgresql://localhost:5432/MJUT
    username: postgres
    password: Welcome@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect