camunda:
  client:
    mode: saas
    auth:
      client-id:
      client-secret:
    cloud:
      cluster-id:
      region: lhr-1
  task-list-url: https://${camunda.client.cloud.region}.tasklist.camunda.io/${camunda.client.cloud.cluster-id}/
  zeebe-rest-address: https://${camunda.client.cloud.region}.zeebe.camunda.io/${camunda.client.cloud.cluster-id}/
  process-definition-id: createInstanceProcessId

server:
  port: 8888
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            #            scope: .default
            scope: openid, profile, email, User.Read
            redirect-uri: http://localhost:8888/login/oauth2/code/azure
        provider:
          azure:
            issuer-uri:
            authorization-uri: https://login.microsoftonline.com/${tenant-Id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${tenant-id}/oauth2/v2.0/token
            user-name-attribute: name

  #redirect-uri: http://localhost:8888/login/oauth2/code/azure


  datasource:
    url: jdbc:postgresql://localhost:5432/MJUT
    username: postgres
    password: Welcome@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect